@ProjectsApi_HostAddress = http://localhost:8002/api

GET {{ProjectsApi_HostAddress}}/popularIndicators/3
Accept: application/json

###


GET {{ProjectsApi_HostAddress}}/users/1/settings/
Accept: application/json

###

PUT {{ProjectsApi_HostAddress}}/users/1/projects
Content-Type: application/json

{
"Name": "New Project111",
"Charts": [
    {
        "Symbol": "New symbol",
        "Timeframe": "new timeframe",
        "Indicators": [
            {
            "Name": "Second user #2",
            "Parameters": "new parameters"
            }
        ]
    }
  ]
}

###
